using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Text.Json;
using SkiaSharp;

namespace Jellyfin.Plugin.JellyfinEnhanced.Services.PosterTags.Rendering
{
    /// <summary>
    /// The renderer's embedded assets (Assets/PosterTags, generated by scripts/build_poster_assets.py): jellyfin-web's
    /// Noto Sans Bold, Material icon outlines, the Rotten Tomatoes marks, flag-icons rasters and JE's colour tables.
    /// Fonts, paths and tables load once; flags decode on first use and stay cached. Thread-safe after construction.
    /// </summary>
    internal sealed class PosterTagAssets : IDisposable
    {
        internal const string ResourcePrefix = "Jellyfin.Plugin.JellyfinEnhanced.Assets.PosterTags.";

        private static readonly Assembly ResourceAssembly = typeof(PosterTagAssets).Assembly;

        private readonly ConcurrentDictionary<string, Lazy<SKImage?>> _flags = new(StringComparer.Ordinal);
        private readonly HashSet<string> _flagCodes;
        private readonly Dictionary<string, PosterTagIcon> _icons;
        private readonly Dictionary<string, PosterTagVectorIcon> _vectorIcons;
        private bool _disposed;

        private PosterTagAssets(
            SKTypeface textTypeface,
            Dictionary<string, PosterTagIcon> icons,
            Dictionary<string, PosterTagVectorIcon> vectorIcons,
            HashSet<string> flagCodes,
            Dictionary<string, (SKColor Background, SKColor Text)> qualityColours,
            string[] qualityCompositeBases,
            Dictionary<string, AgeRatingStyle> ageRatingStyles)
        {
            TextTypeface = textTypeface;
            TextMetrics = PosterTagFontMetrics.From(textTypeface);
            _icons = icons;
            _vectorIcons = vectorIcons;
            _flagCodes = flagCodes;
            QualityColours = qualityColours;
            QualityCompositeBases = qualityCompositeBases;
            AgeRatingStyles = ageRatingStyles;
        }

        /// <summary>Noto Sans Bold (every tag text is 700; CSS 600 resolves to the same face).</summary>
        public SKTypeface TextTypeface { get; }

        public PosterTagFontMetrics TextMetrics { get; }

        /// <summary>qualityColors from qualitytags.js (plus LOW-RES), keyed by the exact label.</summary>
        public IReadOnlyDictionary<string, (SKColor Background, SKColor Text)> QualityColours { get; }

        /// <summary>Audio codec labels whose "&lt;codec&gt; &lt;channels&gt;" variants share the codec's colour.</summary>
        public IReadOnlyList<string> QualityCompositeBases { get; }

        /// <summary>css/ratings.css colours keyed by rating (case-sensitive, like the CSS attribute selector).</summary>
        public IReadOnlyDictionary<string, AgeRatingStyle> AgeRatingStyles { get; }

        /// <summary>Loads every eager asset from the plugin assembly's manifest resources.</summary>
        public static PosterTagAssets Load()
        {
            SKTypeface? typeface = null;
            var icons = new Dictionary<string, PosterTagIcon>(StringComparer.Ordinal);
            var vectors = new Dictionary<string, PosterTagVectorIcon>(StringComparer.Ordinal);
            try
            {
                typeface = LoadBrotliTypeface("fonts.NotoSans-Bold.ttf.br");
                LoadIcons(icons);
                LoadVectorIcons(vectors);
                var (qualityColours, bases) = LoadQualityColours();
                var ageStyles = LoadAgeRatingStyles();

                var flagCodes = new HashSet<string>(StringComparer.Ordinal);
                const string flagPrefix = ResourcePrefix + "flags.";
                foreach (var name in ResourceAssembly.GetManifestResourceNames())
                {
                    if (name.StartsWith(flagPrefix, StringComparison.Ordinal) && name.EndsWith(".webp", StringComparison.Ordinal))
                    {
                        flagCodes.Add(name.Substring(flagPrefix.Length, name.Length - flagPrefix.Length - ".webp".Length));
                    }
                }

                return new PosterTagAssets(typeface, icons, vectors, flagCodes, qualityColours, bases, ageStyles);
            }
            catch
            {
                typeface?.Dispose();
                foreach (var icon in icons.Values)
                {
                    icon.Dispose();
                }

                foreach (var vector in vectors.Values)
                {
                    vector.Dispose();
                }

                throw;
            }
        }

        /// <summary>Looks up an icon by its icons.json key (genre icon name, or "Family:name" for the others).</summary>
        public PosterTagIcon? GetIcon(string key) => _icons.TryGetValue(key, out var icon) ? icon : null;

        public PosterTagVectorIcon? GetVectorIcon(string key) => _vectorIcons.TryGetValue(key, out var icon) ? icon : null;

        /// <summary>True when a flag raster exists for <paramref name="code"/> (flag-icons code or "zxx").</summary>
        public bool HasFlag(string code) => _flagCodes.Contains(code);

        /// <summary>
        /// The decoded 160x120 flag raster, or null when the code is unknown or fails to decode. The image is owned by
        /// this instance; callers must not dispose it.
        /// </summary>
        public SKImage? GetFlag(string code)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (!_flagCodes.Contains(code))
            {
                return null;
            }

            return _flags.GetOrAdd(code, c => new Lazy<SKImage?>(() => DecodeFlag(c), System.Threading.LazyThreadSafetyMode.ExecutionAndPublication)).Value;
        }

        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;
            foreach (var lazy in _flags.Values)
            {
                if (lazy.IsValueCreated)
                {
                    lazy.Value?.Dispose();
                }
            }

            _flags.Clear();
            foreach (var icon in _icons.Values)
            {
                icon.Dispose();
            }

            foreach (var vector in _vectorIcons.Values)
            {
                vector.Dispose();
            }

            TextTypeface.Dispose();
        }

        private static SKImage? DecodeFlag(string code)
        {
            var bytes = ReadResource("flags." + code + ".webp");
            using var data = SKData.CreateCopy(bytes);
            using var codec = SKCodec.Create(data);
            if (codec is null)
            {
                return null;
            }

            // Decode now, into one known pixel format, so concurrent draws share an immutable raster the scaler can read.
            var info = new SKImageInfo(codec.Info.Width, codec.Info.Height, SKColorType.Rgba8888, SKAlphaType.Premul);
            using var bitmap = SKBitmap.Decode(codec, info);
            return bitmap is null ? null : SKImage.FromPixelCopy(bitmap.Info, bitmap.GetPixels(), bitmap.RowBytes);
        }

        private static Stream OpenResource(string name)
        {
            return ResourceAssembly.GetManifestResourceStream(ResourcePrefix + name)
                ?? throw new FileNotFoundException($"Embedded poster tag asset missing: {ResourcePrefix}{name}");
        }

        private static byte[] ReadResource(string name)
        {
            using var stream = OpenResource(name);
            using var buffer = new MemoryStream(stream.CanSeek ? (int)stream.Length : 0);
            stream.CopyTo(buffer);
            return buffer.ToArray();
        }

        private static SKTypeface LoadBrotliTypeface(string name)
        {
            byte[] font;
            using (var stream = OpenResource(name))
            using (var brotli = new BrotliStream(stream, CompressionMode.Decompress))
            using (var buffer = new MemoryStream())
            {
                brotli.CopyTo(buffer);
                font = buffer.ToArray();
            }

            using var data = SKData.CreateCopy(font);
            return SKTypeface.FromData(data) ?? throw new InvalidDataException($"Poster tag font {name} could not be loaded");
        }

        private static JsonDocument ReadJson(string name)
        {
            using var stream = OpenResource(name);
            return JsonDocument.Parse(stream);
        }

        private static void LoadIcons(Dictionary<string, PosterTagIcon> icons)
        {
            using var doc = ReadJson("icons.json");
            foreach (var entry in doc.RootElement.EnumerateObject())
            {
                var e = entry.Value;
                var path = SKPath.ParseSvgPathData(e.GetProperty("path").GetString() ?? string.Empty)
                    ?? throw new InvalidDataException($"Icon {entry.Name} has invalid path data");
                icons[entry.Name] = new PosterTagIcon(
                    path,
                    e.GetProperty("unitsPerEm").GetSingle(),
                    e.GetProperty("ascent").GetSingle(),
                    e.GetProperty("descent").GetSingle(),
                    e.GetProperty("advance").GetSingle());
            }
        }

        private static void LoadVectorIcons(Dictionary<string, PosterTagVectorIcon> vectors)
        {
            using var doc = ReadJson("vector-icons.json");
            foreach (var entry in doc.RootElement.EnumerateObject())
            {
                var vb = entry.Value.GetProperty("viewBox");
                var viewBox = SKRect.Create(vb[0].GetSingle(), vb[1].GetSingle(), vb[2].GetSingle(), vb[3].GetSingle());
                var parts = new List<(SKPath, SKColor)>();
                foreach (var p in entry.Value.GetProperty("paths").EnumerateArray())
                {
                    var path = SKPath.ParseSvgPathData(p.GetProperty("d").GetString() ?? string.Empty)
                        ?? throw new InvalidDataException($"Vector icon {entry.Name} has invalid path data");
                    parts.Add((path, CssColor.Parse(p.GetProperty("fill").GetString(), SKColors.Black)));
                }

                vectors[entry.Name] = new PosterTagVectorIcon(viewBox, parts);
            }
        }

        private static (Dictionary<string, (SKColor, SKColor)>, string[]) LoadQualityColours()
        {
            using var doc = ReadJson("quality-colours.json");
            var colours = new Dictionary<string, (SKColor, SKColor)>(StringComparer.Ordinal);
            foreach (var entry in doc.RootElement.GetProperty("labels").EnumerateObject())
            {
                colours[entry.Name] = (
                    CssColor.Parse(entry.Value.GetProperty("background").GetString(), SKColors.Transparent),
                    CssColor.Parse(entry.Value.GetProperty("color").GetString(), SKColors.White));
            }

            var bases = new List<string>();
            foreach (var b in doc.RootElement.GetProperty("compositeBases").EnumerateArray())
            {
                bases.Add(b.GetString() ?? string.Empty);
            }

            return (colours, bases.ToArray());
        }

        private static Dictionary<string, AgeRatingStyle> LoadAgeRatingStyles()
        {
            using var doc = ReadJson("age-rating-colours.json");
            var styles = new List<AgeRatingStyle>();
            foreach (var s in doc.RootElement.GetProperty("styles").EnumerateArray())
            {
                styles.Add(AgeRatingStyle.Default.With(
                    s.TryGetProperty("background-color", out var bg) ? bg.GetString() : null,
                    s.TryGetProperty("border-color", out var border) ? border.GetString() : null,
                    s.TryGetProperty("color", out var color) ? color.GetString() : null,
                    s.TryGetProperty("text-shadow", out var shadow) ? shadow.GetString() : null));
            }

            var ratings = new Dictionary<string, AgeRatingStyle>(StringComparer.Ordinal);
            foreach (var r in doc.RootElement.GetProperty("ratings").EnumerateObject())
            {
                ratings[r.Name] = styles[r.Value.GetInt32()];
            }

            return ratings;
        }
    }

    /// <summary>Vertical font metrics in font units, as Blink reads them (ascent/descent rounded per size).</summary>
    internal readonly record struct PosterTagFontMetrics(float UnitsPerEm, float Ascent, float Descent)
    {
        public static PosterTagFontMetrics From(SKTypeface typeface)
        {
            float upm = typeface.UnitsPerEm > 0 ? typeface.UnitsPerEm : 1000f;
            using var font = new SKFont(typeface, upm) { Hinting = SKFontHinting.None, LinearMetrics = true };
            var m = font.Metrics;
            return new PosterTagFontMetrics(upm, -m.Ascent, m.Descent);
        }

        /// <summary>
        /// Baseline offset from the top of a line box <paramref name="lineHeight"/> high, for text of
        /// <paramref name="fontSize"/>: half-leading + ascent, with ascent and descent rounded to whole px as Blink does
        /// on Linux/Android.
        /// </summary>
        public float BaselineOffset(float fontSize, float lineHeight)
        {
            float a = PosterTagCss.RoundHalfUp(Ascent / UnitsPerEm * fontSize);
            float d = PosterTagCss.RoundHalfUp(Descent / UnitsPerEm * fontSize);
            // Half the leading above the text. Blink floors it during layout (CalculateLeadingSpace), but the glyphs in the
            // real jellyfin-web captures sit where the unfloored value puts them, so the paint position uses that.
            return ((lineHeight - (a + d)) / 2f) + a;
        }
    }

    /// <summary>A Material icon outline in font units, y down from the font's ascent.</summary>
    internal sealed class PosterTagIcon : IDisposable
    {
        public PosterTagIcon(SKPath path, float unitsPerEm, float ascent, float descent, float advance)
        {
            Path = path;
            Metrics = new PosterTagFontMetrics(unitsPerEm, ascent, descent);
            Advance = advance;
            // Compute the lazily cached bounds and convexity now, so concurrent draws only read the path.
            _ = path.Bounds;
            _ = path.TightBounds;
            _ = path.IsConvex;
        }

        public SKPath Path { get; }

        public PosterTagFontMetrics Metrics { get; }

        /// <summary>Advance width in font units.</summary>
        public float Advance { get; }

        public void Dispose() => Path.Dispose();
    }

    /// <summary>A multi-colour SVG icon (Rotten Tomatoes) as filled paths in its viewBox.</summary>
    internal sealed class PosterTagVectorIcon : IDisposable
    {
        public PosterTagVectorIcon(SKRect viewBox, IReadOnlyList<(SKPath Path, SKColor Fill)> parts)
        {
            ViewBox = viewBox;
            Parts = parts;
            foreach (var (path, _) in parts)
            {
                _ = path.Bounds;
                _ = path.TightBounds;
                _ = path.IsConvex;
            }
        }

        public SKRect ViewBox { get; }

        public IReadOnlyList<(SKPath Path, SKColor Fill)> Parts { get; }

        public void Dispose()
        {
            foreach (var (path, _) in Parts)
            {
                path.Dispose();
            }
        }
    }

    /// <summary>Colours of an age rating badge (ageratingtags.js base rule overridden by a ratings.css rule).</summary>
    internal sealed record AgeRatingStyle(SKColor Background, SKColor Border, SKColor Text, bool TextShadow)
    {
        /// <summary>The badge's own rule: #607D8B, 1px rgba(255,255,255,.25) border, white text with a 2px shadow.</summary>
        public static AgeRatingStyle Default { get; } = new(
            new SKColor(0x60, 0x7D, 0x8B),
            new SKColor(255, 255, 255, CssColor.AlphaByte(0.25f)),
            SKColors.White,
            true);

        public AgeRatingStyle With(string? background, string? border, string? text, string? textShadow)
        {
            return new AgeRatingStyle(
                CssColor.Parse(background, Background),
                CssColor.Parse(border, Border),
                CssColor.Parse(text, Text),
                textShadow is null ? TextShadow : !string.Equals(textShadow.Trim(), "none", StringComparison.OrdinalIgnoreCase));
        }
    }
}
