using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Jellyfin.Plugin.JellyfinEnhanced.Configuration;
using Jellyfin.Plugin.JellyfinEnhanced.Model;
using MediaBrowser.Common.Configuration;
using MediaBrowser.Controller;

namespace Jellyfin.Plugin.JellyfinEnhanced.Services
{
    /// <summary>
    /// Builds and sends the opt-in usage report. BuildPayload is the single
    /// source of truth for what goes out: the config page's preview panel
    /// and the real send both call it, so they can't drift apart. Unlike
    /// GetPublicConfig()'s hand-picked allowlist, the config-flag section here
    /// is generated by reflecting over every bool on PluginConfiguration, so
    /// adding a feature toggle elsewhere doesn't require touching this file.
    /// Send failures only ever get a warning log; this must never be visible
    /// to a user or block anything else the plugin does.
    /// </summary>
    public class AnalyticsReportingService
    {
        // Supabase project dedicated to this plugin's community analytics.
        // The publishable/anon key is meant to ship in clients; RLS with no
        // policies blocks direct table access; report_stats() is SECURITY
        // DEFINER and is the only way this key can write anything.
        private const string SupabaseUrl = "https://nxacdgtrnbqucbvlnhcz.supabase.co";
        private const string SupabaseAnonKey = "sb_publishable_C69ZHubKpz8moyoh3I11Jg_g3MM5hsw";

        private static readonly TimeSpan RequestTimeout = TimeSpan.FromSeconds(15);

        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IApplicationPaths _applicationPaths;
        private readonly IServerApplicationHost _appHost;
        private readonly UsageEventCounterService _counters;
        private readonly UserConfigurationManager _userConfigurationManager;
        private readonly Logger _logger;

        public AnalyticsReportingService(
            IHttpClientFactory httpClientFactory,
            IApplicationPaths applicationPaths,
            IServerApplicationHost appHost,
            UsageEventCounterService counters,
            UserConfigurationManager userConfigurationManager,
            Logger logger)
        {
            _httpClientFactory = httpClientFactory;
            _applicationPaths = applicationPaths;
            _appHost = appHost;
            _counters = counters;
            _userConfigurationManager = userConfigurationManager;
            _logger = logger;
        }

        private static string JellyfinTarget =>
#if NET10_0_OR_GREATER
            "jf12";
#else
            "jf10";
#endif

        private string PluginConfigDir =>
            Path.Join(_applicationPaths.PluginsPath, "configurations", "Jellyfin.Plugin.JellyfinEnhanced");

        /// <summary>
        /// Registers this install with the backend if it hasn't been already
        /// (idempotent, no-ops once AnalyticsInstallId/AnalyticsInstallSecret
        /// are both set). The server mints BOTH the install id and a
        /// high-entropy secret; the client never chooses its own id. Every
        /// subsequent report_stats call must present the secret, which the
        /// backend verifies against a stored hash. This is what stops one
        /// install from overwriting or hijacking another's data by guessing
        /// or reusing its id, since the id alone is no longer sufficient
        /// credential. Must be called (and awaited) before BuildPayload
        /// whenever a real send or preview is about to happen.
        /// </summary>
        public async Task EnsureRegisteredAsync(PluginConfiguration config, CancellationToken cancellationToken)
        {
            if (!string.IsNullOrEmpty(config.AnalyticsInstallId) && !string.IsNullOrEmpty(config.AnalyticsInstallSecret))
            {
                return;
            }

            try
            {
                var client = _httpClientFactory.CreateClient();
                client.Timeout = RequestTimeout;

                using var request = new HttpRequestMessage(HttpMethod.Post, $"{SupabaseUrl}/rest/v1/rpc/register_install");
                request.Headers.Add("apikey", SupabaseAnonKey);
                request.Headers.Add("Authorization", $"Bearer {SupabaseAnonKey}");
                request.Content = new StringContent("{}", Encoding.UTF8, "application/json");

                using var response = await client.SendAsync(request, cancellationToken).ConfigureAwait(false);
                if (!response.IsSuccessStatusCode)
                {
                    _logger.Warning($"[Analytics] Registration failed with status {(int)response.StatusCode}");
                    return;
                }

                var body = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                using var doc = JsonDocument.Parse(body);
                var row = doc.RootElement[0];

                config.AnalyticsInstallId = row.GetProperty("install_id").GetString() ?? string.Empty;
                config.AnalyticsInstallSecret = row.GetProperty("secret").GetString() ?? string.Empty;
                JellyfinEnhanced.Instance?.SaveConfiguration();
                _logger.Info("[Analytics] Registered a new install with the community analytics backend.");
            }
            catch (OperationCanceledException)
            {
                // Shutdown path, silent.
            }
            catch (HttpRequestException ex)
            {
                _logger.Warning($"[Analytics] Registration failed: {ex.Message}");
            }
            catch (JsonException ex)
            {
                _logger.Warning($"[Analytics] Registration failed: unexpected response shape ({ex.Message})");
            }
        }

        /// <summary>
        /// Builds the payload using the ADMIN'S SAVED category toggles. This is
        /// what the real scheduled send uses. Callers must have already
        /// awaited EnsureRegisteredAsync; this method itself does no I/O.
        /// </summary>
        public AnalyticsPayload BuildPayload(PluginConfiguration config) =>
            BuildPayload(config, config.AnalyticsShareFeatureFlags, config.AnalyticsShareUsageCounts, config.AnalyticsShareDataSizes);

        /// <summary>
        /// Builds the payload using EXPLICITLY PASSED category flags rather than
        /// the saved config. The config-page preview panel calls this with
        /// whatever the checkboxes currently show in the browser, including
        /// unsaved changes, so toggling a checkbox and clicking Preview
        /// reflects that choice immediately, without first requiring Save.
        /// Everything else (install id, versions, counters, file sizes) still
        /// reflects real current state either way. Callers must have already
        /// awaited EnsureRegisteredAsync.
        /// </summary>
        public AnalyticsPayload BuildPayload(PluginConfiguration config, bool shareFeatureFlags, bool shareUsageCounts, bool shareDataSizes)
        {
            var (periodStart, counters) = _counters.GetSnapshot();

            var payload = new AnalyticsPayload
            {
                InstallId = config.AnalyticsInstallId,
                PluginVersion = JellyfinEnhanced.Instance?.Version?.ToString(3) ?? string.Empty,
                JellyfinVersion = _appHost.ApplicationVersionString ?? string.Empty,
                JellyfinTarget = JellyfinTarget,
                Period = periodStart,
            };

            if (shareFeatureFlags)
            {
                payload.Config = GetBooleanFeatureFlags(config);
                payload.Settings = GetStringSettings(config);
            }

            if (shareUsageCounts)
            {
                var events = counters
                    .Select(kvp => new UsageEventEntry { Key = kvp.Key, Count = kvp.Value })
                    .ToList();
                events.AddRange(GetTotalCounts());
                payload.Events = events;
            }

            if (shareDataSizes)
            {
                payload.DataFileSizes = GetDataFileSizes();
            }

            return payload;
        }

        /// <summary>
        /// Every bool property on PluginConfiguration except this feature's own
        /// (Analytics*) internal state and any property explicitly marked
        /// [AnalyticsExclude] (internal bookkeeping with no admin-facing
        /// control, e.g. *CustomTabJeOwned), plus two derived "is a key
        /// configured" booleans that mirror GetPublicConfig()'s
        /// TmdbEnabled/MdblistEnabled. The actual keys are strings and must
        /// never be reflected in GetStringSettings, only whether one is present.
        /// </summary>
        private static Dictionary<string, bool> GetBooleanFeatureFlags(PluginConfiguration config)
        {
            var flags = typeof(PluginConfiguration)
                .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                .Where(p => p.PropertyType == typeof(bool)
                    && !p.Name.StartsWith("Analytics", StringComparison.Ordinal)
                    && p.GetCustomAttribute<Model.AnalyticsExcludeAttribute>() == null)
                .ToDictionary(p => p.Name, p => (bool)p.GetValue(config)!);

            flags["TmdbEnabled"] = !string.IsNullOrWhiteSpace(config.TMDB_API_KEY);
            flags["MdblistEnabled"] = !string.IsNullOrWhiteSpace(config.MdblistApiKey);

            return flags;
        }

        /// <summary>
        /// Every string property explicitly marked [AnalyticsInclude]. See that
        /// attribute's doc comment for why strings can't auto-include by type
        /// the way bools do. Empty/null values are skipped so a never-set field
        /// doesn't crowd out real answers in the dashboard's value-distribution view.
        /// </summary>
        private static Dictionary<string, string> GetStringSettings(PluginConfiguration config)
        {
            return typeof(PluginConfiguration)
                .GetProperties(BindingFlags.Public | BindingFlags.Instance)
                .Where(p => p.PropertyType == typeof(string) && p.GetCustomAttribute<Model.AnalyticsIncludeAttribute>() != null)
                .Select(p => new { p.Name, Value = p.GetValue(config) as string })
                .Where(x => !string.IsNullOrEmpty(x.Value))
                .ToDictionary(x => x.Name, x => x.Value!);
        }

        /// <summary>
        /// Deliberately narrow. activity.json/awards.json/mdblist-ratings.json/
        /// tag-cache.json all scale with library size, not with whether the
        /// feature is actually used; their size tells you nothing an
        /// admin's library size doesn't already explain, so they're excluded.
        /// reviews.json moved to GetTotalCounts() (a review count, gated by
        /// AnalyticsShareUsageCounts, is a more direct "is this used" signal
        /// than its byte size ever was). custom_branding's total size answers
        /// the same "is this used" question for uploaded logo/banner/favicon
        /// images: the toggle can be on with nothing ever uploaded.
        /// </summary>
        private Dictionary<string, long> GetDataFileSizes()
        {
            var sizes = new Dictionary<string, long>();

            try
            {
                var brandingDir = JellyfinEnhanced.BrandingDirectory;
                sizes["custom_branding"] = !string.IsNullOrEmpty(brandingDir) && Directory.Exists(brandingDir)
                    ? new DirectoryInfo(brandingDir).EnumerateFiles("*", SearchOption.AllDirectories).Sum(f => f.Length)
                    : 0;
            }
            catch
            {
                sizes["custom_branding"] = 0;
            }

            return sizes;
        }

        /// <summary>
        /// Point-in-time item counts, not per-period deltas. Unlike the
        /// incrementing counters in UsageEventCounterService (e.g.
        /// "seerr.request_submitted", which resets every report), these read the
        /// CURRENT total straight off disk every time a report goes out. Keys
        /// are prefixed "total." specifically so they can never collide with,
        /// or be misread as, a per-period delta on the dashboard. Never
        /// per-user data, only aggregate counts across every GetAllUserIds()
        /// folder (or, for reviews, the single shared reviews.json).
        /// Adoption ("how many installs actually have any of this") is
        /// deliberately NOT computed here -- it doesn't need per-user
        /// scanning at all, since the backend can already derive "how many
        /// reporting installs have total.bookmarks > 0" straight from this
        /// one per-install number via v_feature_usage_totals. See that view.
        /// </summary>
        private List<UsageEventEntry> GetTotalCounts()
        {
            var userIds = _userConfigurationManager.GetAllUserIds();

            long bookmarks = 0;
            long hiddenContentItems = 0;
            long spoilerBlurItems = 0;

            foreach (var userId in userIds)
            {
                bookmarks += _userConfigurationManager
                    .GetUserConfiguration<UserBookmark>(userId, "bookmark.json").Bookmarks.Count;

                hiddenContentItems += _userConfigurationManager
                    .GetUserConfiguration<UserHiddenContent>(userId, "hidden-content.json").Items.Count;

                var blur = _userConfigurationManager
                    .GetUserConfiguration<UserSpoilerBlur>(userId, SpoilerBlurImageFilter.SpoilerBlurFileName);
                spoilerBlurItems += blur.Series.Count + blur.Movies.Count + blur.Collections.Count;
            }

            long reviews = _userConfigurationManager.GetAllReviews().Reviews.Count;

            return new List<UsageEventEntry>
            {
                new UsageEventEntry { Key = "total.bookmarks", Count = (int)bookmarks },
                new UsageEventEntry { Key = "total.hidden_content_items", Count = (int)hiddenContentItems },
                new UsageEventEntry { Key = "total.spoiler_blur_items", Count = (int)spoilerBlurItems },
                new UsageEventEntry { Key = "total.reviews", Count = (int)reviews },
            };
        }

        /// <summary>
        /// Runs on the scheduled task's cadence: no-ops unless analytics is
        /// enabled, AND either the configured interval has actually elapsed
        /// since the last successful send, OR the plugin version has changed
        /// since that last send. The version check exists because
        /// v_version_adoption is only useful if it reflects upgrades promptly;
        /// otherwise "how fast is everyone updating" would lag by up to 30
        /// days behind reality, which defeats the point of tracking it at all.
        /// </summary>
        public async Task ReportIfDueAsync(CancellationToken cancellationToken)
        {
            var instance = JellyfinEnhanced.Instance;
            var config = instance?.Configuration;
            if (config == null || !config.AnalyticsEnabled) return;

            var currentPluginVersion = instance.Version?.ToString(3) ?? string.Empty;
            var versionChanged = !string.IsNullOrEmpty(config.AnalyticsLastReportedPluginVersion)
                && config.AnalyticsLastReportedPluginVersion != currentPluginVersion;

            var intervalDays = Math.Clamp(config.AnalyticsReportIntervalDays, 7, 30);
            var lastSent = config.AnalyticsLastReportedAt > 0
                ? DateTimeOffset.FromUnixTimeMilliseconds(config.AnalyticsLastReportedAt)
                : (DateTimeOffset?)null;

            var intervalElapsed = !lastSent.HasValue || DateTimeOffset.UtcNow - lastSent.Value >= TimeSpan.FromDays(intervalDays);

            if (!intervalElapsed && !versionChanged)
            {
                return;
            }

            await SendAsync(config, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Sends a report right now, bypassing the interval/version due-check.
        /// Used for the OFF-&gt;ON toggle transition: AnalyticsLastReportedAt/
        /// AnalyticsLastReportedPluginVersion survive a disable, so on a
        /// re-enable ReportIfDueAsync can correctly decide nothing is "due"
        /// and skip sending, which would also skip clearing opted_out on
        /// the backend, since only a real report_stats call does that. A
        /// re-enable must always send, regardless of when the last report went out.
        /// </summary>
        public Task ForceSendAsync(CancellationToken cancellationToken)
        {
            var config = JellyfinEnhanced.Instance?.Configuration;
            if (config == null || !config.AnalyticsEnabled) return Task.CompletedTask;

            return SendAsync(config, cancellationToken);
        }

        private async Task SendAsync(PluginConfiguration config, CancellationToken cancellationToken)
        {
            await EnsureRegisteredAsync(config, cancellationToken).ConfigureAwait(false);
            if (string.IsNullOrEmpty(config.AnalyticsInstallId) || string.IsNullOrEmpty(config.AnalyticsInstallSecret))
            {
                _logger.Warning("[Analytics] Skipping report: registration did not complete.");
                return;
            }

            var payload = BuildPayload(config);

            try
            {
                var rpcBody = new Dictionary<string, object?>
                {
                    ["p_install_id"] = payload.InstallId,
                    ["p_secret"] = config.AnalyticsInstallSecret,
                    ["p_plugin_version"] = payload.PluginVersion,
                    ["p_jellyfin_version"] = payload.JellyfinVersion,
                    ["p_jellyfin_target"] = payload.JellyfinTarget,
                    ["p_config"] = payload.Config,
                    ["p_settings"] = payload.Settings,
                    ["p_period"] = payload.Period,
                    ["p_events"] = payload.Events,
                    ["p_data_file_sizes"] = payload.DataFileSizes,
                };

                var client = _httpClientFactory.CreateClient();
                client.Timeout = RequestTimeout;

                using var request = new HttpRequestMessage(HttpMethod.Post, $"{SupabaseUrl}/rest/v1/rpc/report_stats");
                request.Headers.Add("apikey", SupabaseAnonKey);
                request.Headers.Add("Authorization", $"Bearer {SupabaseAnonKey}");
                request.Content = new StringContent(JsonSerializer.Serialize(rpcBody), Encoding.UTF8, "application/json");

                using var response = await client.SendAsync(request, cancellationToken).ConfigureAwait(false);
                if (!response.IsSuccessStatusCode)
                {
                    _logger.Warning($"[Analytics] Report failed with status {(int)response.StatusCode}");

                    // 403 means the backend has no row matching this install id
                    // + secret pair (e.g. it was removed server-side). Without
                    // this, a install stuck in that state would fail forever --
                    // EnsureRegisteredAsync only registers when the local id/
                    // secret are EMPTY, and they aren't here, just stale.
                    // Clearing them makes the next attempt register fresh.
                    if (response.StatusCode == System.Net.HttpStatusCode.Forbidden)
                    {
                        config.AnalyticsInstallId = string.Empty;
                        config.AnalyticsInstallSecret = string.Empty;
                        JellyfinEnhanced.Instance?.SaveConfiguration();
                        _logger.Warning("[Analytics] Backend rejected our credentials; will re-register on the next attempt.");
                    }

                    return;
                }

                // Success: start a fresh counting period and record when/what was sent.
                var newPeriod = DateTime.UtcNow.ToString("yyyy-MM-dd");
                _counters.ResetForNewPeriod(newPeriod);

                config.AnalyticsLastReportedAt = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
                config.AnalyticsLastPayloadJson = JsonSerializer.Serialize(payload);
                config.AnalyticsLastReportedPluginVersion = payload.PluginVersion;
                JellyfinEnhanced.Instance?.SaveConfiguration();

                _logger.Info("[Analytics] Report sent successfully.");
            }
            catch (OperationCanceledException)
            {
                // Shutdown path, silent.
            }
            catch (HttpRequestException ex)
            {
                _logger.Warning($"[Analytics] Report failed: {ex.Message}");
            }
            catch (JsonException ex)
            {
                _logger.Warning($"[Analytics] Report failed: payload serialization error ({ex.Message})");
            }
        }

        /// <summary>
        /// Fired once when the admin turns the master toggle OFF (see
        /// JellyfinEnhanced.UpdateConfiguration). Flags this install's row as
        /// opted out on the backend, so every public view excludes it from
        /// then on, without deleting anything. No-ops if this install was
        /// never registered (nothing to flag). Turning the toggle back on
        /// later needs no corresponding "resume" call: the next real
        /// report_stats send clears the flag on its own.
        /// </summary>
        public async Task SendOptOutAsync(PluginConfiguration config, CancellationToken cancellationToken)
        {
            if (string.IsNullOrEmpty(config.AnalyticsInstallId) || string.IsNullOrEmpty(config.AnalyticsInstallSecret))
            {
                return;
            }

            try
            {
                var rpcBody = new Dictionary<string, object?>
                {
                    ["p_install_id"] = config.AnalyticsInstallId,
                    ["p_secret"] = config.AnalyticsInstallSecret,
                };

                var client = _httpClientFactory.CreateClient();
                client.Timeout = RequestTimeout;

                using var request = new HttpRequestMessage(HttpMethod.Post, $"{SupabaseUrl}/rest/v1/rpc/set_opted_out");
                request.Headers.Add("apikey", SupabaseAnonKey);
                request.Headers.Add("Authorization", $"Bearer {SupabaseAnonKey}");
                request.Content = new StringContent(JsonSerializer.Serialize(rpcBody), Encoding.UTF8, "application/json");

                using var response = await client.SendAsync(request, cancellationToken).ConfigureAwait(false);
                if (!response.IsSuccessStatusCode)
                {
                    _logger.Warning($"[Analytics] Opt-out flag failed with status {(int)response.StatusCode}");
                    return;
                }

                _logger.Info("[Analytics] Flagged this install as opted out.");
            }
            catch (OperationCanceledException)
            {
                // Shutdown path, silent.
            }
            catch (HttpRequestException ex)
            {
                _logger.Warning($"[Analytics] Opt-out flag failed: {ex.Message}");
            }
            catch (JsonException ex)
            {
                _logger.Warning($"[Analytics] Opt-out flag failed: payload serialization error ({ex.Message})");
            }
        }
    }
}
